### ISSUE TITLE
Author section is not rendered

### ISSUE THREAD

**Issue by Neftedollar** [LambdaFactory/Fornax#17]
I've add 
`author: Neftedollar`
to the index file's metadata but it not rendered.
Also if I use link `author: [Link text](http://example.com)` parser fails 
```sh
fornax_try fornax watch
[00:46:28] '/Users/neftedollar/dev/fornax_try/_public/archive.html' generated in 152ms
[00:46:28] '/Users/neftedollar/dev/fornax_try/_public/index.html' generated in 144ms

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> YamlDotNet.Core.SemanticErrorException: (Line: 3, Col: 25, Idx: 95) - (Line: 3, Col: 44, Idx: 114): While parsing a block mapping, did not find expected key.
   at YamlDotNet.Core.Parser.ParseBlockMappingKey(Boolean isFirst)
   at YamlDotNet.Core.Parser.MoveNext()
   at YamlDotNet.Core.ParserExtensions.SkipThisAndNestedEvents(IParser parser)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Generator.ContentParser.parse(String fileContent, Type modelType) in D:\Programowanie\Projekty\Fornax\src\Fornax\Generator.fs:line 214
   at Generator.Utils.memoizeParser@22.Invoke(String x, Type y) in D:\Programowanie\Projekty\Fornax\src\Fornax\Generator.fs:line 27
   at Generator.Evaluator.evaluate[a](a posts, String templatePath, FSharpFunc`2 getSiteModel, FSharpFunc`2 getContentModel) in D:\Programowanie\Projekty\Fornax\src\Fornax\Generator.fs:line 170
   at Generator.generate[a](a posts, String projectRoot, String page) in D:\Programowanie\Projekty\Fornax\src\Fornax\Generator.fs:line 353
   at Generator.generateFolder(String projectRoot) in D:\Programowanie\Projekty\Fornax\src\Fornax\Generator.fs:line 446
   at Fornax.main$cont@77(String[] argv, ArgumentParser`1 parser, Unit unitVar) in D:\Programowanie\Projekty\Fornax\src\Fornax\Fornax.fs:line 112
   at Fornax.main(String[] argv) in D:\Programowanie\Projekty\Fornax\src\Fornax\Fornax.fs:line 72
[1]    8400 abort      fornax watch
```

should I split this issue?

**Comment by Krzysztof-Cieslak** [comment]
Have you added appropriate filed to the F# record modelling metadata? (Probably `Model` type in `index.fsx`)

**Comment by Neftedollar** [comment]
@Krzysztof-Cieslak  thnx! It works.
